import type { Metadata } from "next";
import { inter, quicksand } from "@/components/ui/fonts";
import "./globals.css";
import NavigationWrapper from "../components/ui/navigation/nav-wrapper";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased text-primary`}>
        <header className="flex bg-primary h-10 items-center">
          <div className="container px-5 lg:px-20">
            <NavigationWrapper />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
