import type { Metadata } from "next";
import { inter, quicksand } from "@/app/ui/fonts";
import "./globals.css";
import NavigationWrapper from "./ui/navigation/nav-wrapper";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased text-black`}>
        <header className="flex bg-green-200 h-10 items-center">
          <div className="container px-5 lg:px-20">
            <NavigationWrapper />
          </div>
        </header>
        {children}

        <footer className="flex">
          <h3>CleanUp!!</h3>
          <ul>
            <li>home</li>
            <li>dev</li>
            <li>contribution</li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
